### ISSUE TITLE
постоянно выпадает запрос пароля

### ISSUE THREAD

**Issue by 222mar222** [birdiecode/PassAES#1]
постоянно выпадает запрос пароля, не зависимо от действий в password manager aesPass.

**Comment by birdiecode** [comment]
Вы исползовали pre-alpha версию. в ней установлен кароткий период запроса пароля.

**Comment by birdiecode** [comment]
воспользуйтесь новой версией [https://github.com/birdiecode/aesPass/releases/tag/V1.0.2](https://github.com/birdiecode/aesPass/releases/tag/V1.0.2)
